#ifndef HEADER_SCGUI_BUTTON
#	define HEADER_SCGUI_BUTTON

#	include <SCGUI/style.h>
#	include <SDL2/SDL.h>

enum SCGUI_Alignment {
	SCGUI_ALIGNMENT_RIGHT,
	SCGUI_ALIGNMENT_LEFT,
	SCGUI_ALIGNMENT_CENTER
};

#endif
