#ifndef HEADER_SCGUI_COLOR
#	define HEADER_SCGUI_COLOR

#	define SCGUI_KEY_A SDL_SCANCODE_A
#	define SCGUI_KEY_B SDL_SCANCODE_B
#	define SCGUI_KEY_C SDL_SCANCODE_C
#	define SCGUI_KEY_D SDL_SCANCODE_D
#	define SCGUI_KEY_E SDL_SCANCODE_E
#	define SCGUI_KEY_F SDL_SCANCODE_F
#	define SCGUI_KEY_G SDL_SCANCODE_G
#	define SCGUI_KEY_H SDL_SCANCODE_H
#	define SCGUI_KEY_I SDL_SCANCODE_I
#	define SCGUI_KEY_J SDL_SCANCODE_J
#	define SCGUI_KEY_K SDL_SCANCODE_K
#	define SCGUI_KEY_L SDL_SCANCODE_L
#	define SCGUI_KEY_M SDL_SCANCODE_M
#	define SCGUI_KEY_N SDL_SCANCODE_N
#	define SCGUI_KEY_O SDL_SCANCODE_O
#	define SCGUI_KEY_P SDL_SCANCODE_P
#	define SCGUI_KEY_Q SDL_SCANCODE_Q
#	define SCGUI_KEY_R SDL_SCANCODE_R
#	define SCGUI_KEY_S SDL_SCANCODE_S
#	define SCGUI_KEY_T SDL_SCANCODE_T
#	define SCGUI_KEY_U SDL_SCANCODE_U
#	define SCGUI_KEY_V SDL_SCANCODE_V
#	define SCGUI_KEY_W SDL_SCANCODE_W
#	define SCGUI_KEY_X SDL_SCANCODE_X
#	define SCGUI_KEY_Y SDL_SCANCODE_Y
#	define SCGUI_KEY_Z SDL_SCANCODE_Z
#	define SCGUI_KEY_SPACE SDL_SCANCODE_SPACE
#	define SCGUI_KEY_ENTER SDL_SCANCODE_RETURN

#endif
